### PR TITLE
Dockerfile: alpine rebase, remove build dependencies, added variables

### PR DESCRIPTION
**Pull request by guillaumedsde**
Hi,

I've created an alpine linux based Dockerfile for playmaker, it builds and launches seemingly without a hitch (might be worth testing a bit more). The goal was to make the final image smaller, so far, its down from around 900MB to 671MB. here's a rundown of what I've done

* image based on python:alpine-3 (Python 3 on alpine linux
* use less RUN statements since they create new layers and increase the size
* since fdroidserver isnt in the alpine linux repo, I install it using pip
* remove build time dependencies after pip install
* disable pip cache
* don't use alpine's apk cache
* commented the dockerfile
* added variables to the dockerfile

There might be a couple more ways to make it smaller, I think the biggest elements of it are:
* JDK (is this necessary for running the app or just building?)
* Android SDK (is this necessary for running the app or just building? could we remove parts of it?)

### CODE REVIEW

**Comment by guillaumedsde** [comment]
also I forgot, the UID 999 is taken up by the docker user on my machine, I removed the part that set the UID and the GID in `useradd` was it necessary to set UID to 999?

**Comment by Findus23** [comment]
Hi @guillaumedsde,

I wanted to try out your Dockerfile as I think using the latest fdroidserver will fix some issues (like #33)

But on every `fdroid update` I only get the following error:
`CRITICAL: Java JDK not found! Install in standard location or set java_paths!`

Even commenting out the following in the config.py doesn't change that:
```python
java_paths = {
    '1.8': "/usr/lib/jvm/java-1.8-openjdk",
}
```

Do you have an idea how to solve this?

**Comment by guillaumedsde** [comment]
hi, it looks like alpine's apk package manager is not setting the java environement variable correctly, this might need to be done manually, I'll give it a look in more depth this weekend, but looking at this java dockerfile might be of help :) 
https://github.com/frol/docker-alpine-java/blob/master/Dockerfile

**Comment by Findus23** [comment]
Seems like there is a bit more broken (did you test this with the latest fdroidserver?)

I checked the code arround the exception
```python
    if not (('jarsigner' in config or 'apksigner' in config)                                     
            and 'keytool' in config):                                                                  
        raise FDroidException(_('Java JDK not found! Install in standard location or set java_paths!'))
```
and indeed there is no jarsigner or apksigner in the config.
I manually added `jarsigner="/usr/lib/jvm/java-1.8-openjdk/bin/"` to the config and it worked.

But then a lot of XML errors and a `KeyError: '{http://schemas.android.com/apk/res/android}name'``exception came (and I think I also saw this error when I tried to change the dockerfile to the latest fdroidserver from debian backports)

**Comment by guillaumedsde** [comment]
in the dockerfile I install fdroidserver with Pypi so I think its the latest, a quick fix for testing would be to `pip install -I fdroidserver==<last version that worked>` (in the dockerfile instruction) which version last worked for you?

**Comment by Findus23** [comment]
Well the whole point for me was to get the latest version of fdroidserver to run, so I guess I'll try again when I have more time.

**Comment by guillaumedsde** [comment]
right makes sense, I'll also give it a look this weekend, see if I can try and fix it

**Comment by guillaumedsde** [comment]
exam period ate my time, will give it some time when this is done

**Comment by c64bob** [comment]
Hi @guillaumedsde, hope the exams are going well!

A few things I've found when playing with your new dockerfile:

- fdroid has a problem recognizing java under alpine; for a workaround it is sufficient to add /usr/lib/jvm/java-1.8-openjdk/bin to PATH
- the android SDK doesn't seem to be neccessary, as fdroid will fall back using jarsigner instead of apksigner
- when running fdroid init there was an error that a png from the examples couldn't be found; somehow fdroid does not detect the right directory, as everything that is needed is there

**Comment by Findus23** [comment]
Just FYI, to avoid the issues I was having with the docker image (#33, #43), I have now set up playmaker without docker and it was really easy (only installing it in a virtualenv and installing the latest fdroidserver with pip) and now everything works fine.
So I guess the android-sdk isn't needed.

**Pull request closed without merging**
