### PR TITLE
Enforce SSL client side, support SSL server-side, add mock certificates

### PR DESCRIPTION
**Pull request by n1zzo**

### CODE REVIEW

**Comment by NoMore201** [comment]
For what I understand, forcing the server to load some certificate is already a way to enforce https, so checking for https protocol in javascript is useless, since the server won't start without certificate and won't accept http requests, throwing the following error:

    WARNING:tornado.general:SSL Error on 7 ('127.0.0.1', 34168): [SSL: HTTP_REQUEST] http request (_ssl.c:748)

However, this makes sense if we add a cmdline option to avoid https on the server (for example if we want to setup an https proxy behind the application), and then check on the client if we are using the right protocol. Is this reasoning correct?

**Comment by NoMore201** [comment]
Also, you can use the `$location` angular service [0], already injected into the application initalizing function. In this way you don't have to write long line such as `window.location.protocol.length`.

[0] https://docs.angularjs.org/api/ng/service/$location

**Comment by n1zzo** [comment]
Yeah, you are totally correct about this, we could need to turn off HTTPS to use and external HTTPS proxy, but this makes it necessary to redirect to HTTPS also on client side.
I'm going to add the command line option to disable HTTPS on pm-server and clean up the client-side redirection.

**Comment by n1zzo** [comment]
Ok, I've added the --no-https command line option and used $location in the front-end code.

**Pull request merged**
